import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AdminNav from '@/components/shared/AdminNav';
import Header from '@/components/shared/Header';
import Providers from '@/utils/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-[#F6F7F8]`}>
                <Providers>
                    <div className="flex">
                        <div className="bg-white">
                            <AdminNav />
                        </div>
                        <div className="w-full">
                            <Header />
                            <div className="p-[10px]">{children}</div>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
