import Header from '@/components/shared/Header';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';
import Providers from '@/utils/Providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className} text-sm font-poppin`}>
                <Providers>
                    <Header />
                    <Navbar />
                    {children}
                    <Footer />
                    <ToastContainer position="bottom-right" theme="dark" autoClose={3000} />
                </Providers>
            </body>
        </html>
    );
}
