import Header from '@/components/shared/Header';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';
import Providers from '@/utils/Providers';
import { Provider, useDispatch, useSelector } from 'react-redux';
import store, { AppDispatch } from '@/utils/store';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    <Header />
                    <Navbar />
                    {children}
                    <Footer />
                </body>
            </html>
        </Providers>
    );
}
